# Generated by Django 5.0.1 on 2026-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("forecast_date", models.DateField(db_index=True)),
                ("temp_high", models.FloatField(null=True)),
                ("temp_low", models.FloatField(null=True)),
                ("feels_like_high", models.FloatField(null=True)),
                ("feels_like_low", models.FloatField(null=True)),
                ("weather_code", models.IntegerField(null=True)),
                ("weather_description", models.CharField(blank=True, max_length=100)),
                ("weather_icon", models.CharField(blank=True, max_length=50)),
                ("precipitation_sum", models.FloatField(null=True)),
                ("precipitation_probability", models.IntegerField(null=True)),
                ("wind_speed_max", models.FloatField(null=True)),
                ("wind_gusts_max", models.FloatField(null=True)),
                ("wind_direction_dominant", models.IntegerField(null=True)),
                ("uv_index_max", models.FloatField(null=True)),
                ("sunrise", models.DateTimeField(null=True)),
                ("sunset", models.DateTimeField(null=True)),
                ("cached_until", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Daily Forecast",
                "verbose_name_plural": "Daily Forecasts",
                "ordering": ["forecast_date"],
                "indexes": [
                    models.Index(
                        fields=["lat", "lon", "forecast_date"],
                        name="weather_dai_lat_8de732_idx",
                    ),
                    models.Index(
                        fields=["cached_until"], name="weather_dai_cached__4525d4_idx"
                    ),
                ],
                "unique_together": {("lat", "lon", "source", "forecast_date")},
            },
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "lon",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("observation_time", models.DateTimeField(db_index=True)),
                ("temperature", models.FloatField(null=True)),
                ("feels_like", models.FloatField(null=True)),
                ("dew_point", models.FloatField(null=True)),
                ("humidity", models.IntegerField(null=True)),
                ("pressure", models.FloatField(null=True)),
                ("visibility", models.FloatField(null=True)),
                ("cloud_cover", models.IntegerField(null=True)),
                ("uv_index", models.FloatField(null=True)),
                ("wind_speed", models.FloatField(null=True)),
                ("wind_direction", models.IntegerField(null=True)),
                ("wind_gusts", models.FloatField(null=True)),
                ("weather_code", models.IntegerField(null=True)),
                ("weather_description", models.CharField(blank=True, max_length=100)),
                ("weather_icon", models.CharField(blank=True, max_length=50)),
                ("sunrise", models.DateTimeField(null=True)),
                ("sunset", models.DateTimeField(null=True)),
                ("cached_until", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Weather Observation",
                "verbose_name_plural": "Weather Observations",
                "ordering": ["-observation_time"],
                "indexes": [
                    models.Index(
                        fields=["lat", "lon", "-observation_time"],
                        name="weather_wea_lat_625385_idx",
                    ),
                    models.Index(
                        fields=["cached_until"], name="weather_wea_cached__cc9073_idx"
                    ),
                ],
            },
        ),
    ]
